### ISSUE TITLE
Sending an email in the sbatch script

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/resources#9]
Hi,
would it be possible to add the possibility to send an email within the `sbatch` script
to be notified when the job actually start and stop?

**Comment by emepetres** [comment]
From the sbatch script, I think is a matter of whether the HPC supports it
with some command. @vsande what do you think?

**Comment by victorsndvg** [comment]
Sorry, I didn't see this issue before.

@emepetres , I think you are right. Slurm options enable users to define an email in order to be notified in particular events (job success, etc.).

I think this is one of the cases already described in [cloudify-hpc-plugin/#4](https://github.com/MSO4SC/cloudify-hpc-plugin/issues/4)

**Comment by emepetres** [comment]
Issue moved to [MSO4SC/cloudify-hpc-plugin #46](https://github.com/MSO4SC/cloudify-hpc-plugin/issues/46) via [**ZenHub**](https://www.zenhub.com/)
